# org: naviester
app: cloud-assignment
service: sample-rest-api

frameworkVersion: ">=2.0.0"

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  apiName: ${self:service}
  memorySize: 128 #mb
  timeout: 30 #seconds
  environment:
    REGEX_ORG_NAMES: ${self:custom.regex_value}
    COPYRIGHT_SYMBOL: ${self:custom.copyright_symbol}
  lambdaHashingVersion: 20201221

custom:
  regex_value: (Google|Amazon|Oracle|Microsoft|Deloitte)
  copyright_symbol: \1©

functions:
  appendCopyRight:
    handler: src/copyright_handler.copyright_companies
    name: copyright-symbol-appender
    events:
      - http:
          path: /appendCopyrightSymbol
          method: POST
          cors: true
